name: "[PR] Semantic Pull Request"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check-pullrequest-label:
    name: Check for labeled PR
    runs-on: ubuntu-latest
    steps:
      - name: Platform label
        uses: agilepathway/label-checker@v1.6.65
        with:
          any_of: ci,config,deps,scripts,eslint,prettier,oxlint,biome
          none_of: "@:"
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  check-pullrequest-title:
    name: Check for semantic PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          wip: true
          validateSingleCommit: true
          scopes: |
            ci 
            config
            deps
            scripts
            eslint
            prettier
            oxlint
            biome